const settingActionTypes = {
    APPLICATION_CONFIG_UPDATE: 'APPLICATION_CONFIG_UPDATE',
    SETTING_NEW_VERSION_NOTIFICATION: 'SETTING_NEW_VERSION_NOTIFICATION',
    SETTING_IMPORTANT_NEWS_NOTIFICATION: 'SETTING_IMPORTANT_NEWS_NOTIFICATION',
    LANGUAGE_UPDATE: "LANGUAGE_UPDATE",
    VERSION_INFO_UPDATE: "VERSION_INFO_UPDATE",
    IS_INIT: "IS_INIT",
    TOGGLE_CPU_FLOAT_BUTTON: "TOGGLE_CPU_FLOAT_BUTTON",
    DISCOVERY_ALERT_UPDATE: "DISCOVERY_ALERT_UPDATE",
    GAMES_USED_LIST_UPDATE: "GAMES_USED_LIST_UPDATE",
    DISCOVERY_USED_LIST_UPDATE: "DISCOVERY_USED_LIST_UPDATE",
    APPLICATION_LOCK_STATUS: "APPLICATION_LOCK_STATUS",
    APPLICATION_NUMBER_UNLOCK: "APPLICATION_NUMBER_UNLOCK",
    APPLICATION_LOCK_UPDATE: "APPLICATION_LOCK_UPDATE",
    APPLICATION_LOCK_BIOLOGY_UPDATE: "APPLICATION_LOCK_BIOLOGY_UPDATE",
    APPLICATION_LOCK_BIOLOGY_TYPE: "APPLICATION_LOCK_BIOLOGY_TYPE",
    APPLICATION_LOCK_BACKGROUND_UPDATE: "APPLICATION_LOCK_BACKGROUND_UPDATE",
    APPLICATION_PASSWORD_UPDATE: "APPLICATION_PASSWORD_UPDATE",
    APPLICATION_PASSWORD_TIPS_UPDATE: "APPLICATION_PASSWORD_TIPS_UPDATE",
    APPLICATION_WAITING_URI: "APPLICATION_WAITING_URI",
    APPLICATION_WAITING_COMPONENT: "APPLICATION_WAITING_COMPONENT",
    APPLICATION_REMEMBER_PASSWORD: "APPLICATION_REMEMBER_PASSWORD"
};

export default settingActionTypes;
