const eosActionTypes = {
    EOS_UPDATE_EOS: "EOS_UPDATE_EOS",
    EOS_UPDATE_PSW: "EOS_UPDATE_PSW",

    EOS_UPDATE_SUPPORTEXCHANGES: "EOS_UPDATE_SUPPORTEXCHANGES",
    EOS_UPDATE_NETWORKS: "EOS_UPDATE_NETWORKS",
    EOS_UPDATE_PRICE: "EOS_UPDATE_PRICE",
    EOS_UPDATE_HISTORYNETWORKS: "EOS_UPDATE_HISTORYNETWORKS",

    EOS_UPDATE_RAM_PRICE: "EOS_UPDATE_RAM_PRICE",
    EOS_BUY_RAM: "EOS_BUY_RAM",
    EOS_SELL_RAM: "EOS_SELL_RAM",

    EOS_UPDATE_REX_PRICE: "EOS_UPDATE_REX_PRICE",
    EOS_UPDATE_RENTAL_PRICE: "EOS_UPDATE_RENTAL_PRICE",
    EOS_BUY_REX: "EOS_BUY_REX",
    EOS_SELL_REX: "EOS_SELL_REX",

    EOS_ACCOUNT_UPDATE_INFO: "EOS_ACCOUNT_UPDATE_INFO",
    EOS_ACCOUNT_ADD: 'EOS_ACCOUNT_ADD',
    EOS_ACCOUNT_PASSWORD_CHANGE: 'EOS_ACCOUNT_PASSWORD_CHANGE',
    EOS_ACCOUNT_NETWORK_CHANGE: 'EOS_ACCOUNT_NETWORK_CHANGE',
    EOS_ACCOUNT_REMOVE: 'EOS_ACCOUNT_REMOVE',
    EOS_CURRENT_NETWORK_CHANGE: 'EOS_CURRENT_NETWORK_CHANGE',

    EOS_UPDATE_SUPPORTTOKENS: 'EOS_UPDATE_SUPPORTTOKENS',
    EOS_ACCOUNT_SUPPORT_TOKEN_ADD: 'EOS_ACCOUNT_SUPPORT_TOKEN_ADD',
    EOS_ACCOUNT_SUPPORT_TOKEN_REMOVE: 'EOS_ACCOUNT_SUPPORT_TOKEN_REMOVE',
    EOS_UPDATE_TOKEN_BALANCE: 'EOS_UPDATE_TOKEN_BALANCE',
    EOS_ADD_CUSTOM_TOKEN: 'EOS_ADD_CUSTOM_TOKEN',

    EOS_SECRET_UPDATE: 'EOS_SECRET_UPDATE',

    EOS_TRANSFER_HISTORY_UPDATE: 'EOS_TRANSFER_HISTORY_UPDATE',
    EOS_BROWSER_HISTORY_UPDATE: 'EOS_BROWSER_HISTORY_UPDATE',
    EOS_ASSETS_SHOW_TOGGLE: 'EOS_ASSETS_SHOW_TOGGLE',
    EOS_UPDATE_TOKEN_PRICE: 'EOS_UPDATE_TOKEN_PRICE',

    EOS_RESET_HISTORY_STACK: 'EOS_RESET_HISTORY_STACK',
    EOS_ADDTO_HISTORY_STACK: 'EOS_ADDTO_HISTORY_STACK'
};

export default eosActionTypes;
