# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
    pod 'Bugly'
end

target 'meet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for meet

  #target 'meet-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

  common_pods

  target 'meetTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'meet-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for meet-tvOS

  target 'meet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'meetArchive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for meetArchive
  common_pods

end
