const ethActionTypes = {
    ETH_ACCOUNT_ADD: 'ETH_ACCOUNT_ADD',
    ETH_ACCOUNT_PASSWORD_CHANGE: 'ETH_ACCOUNT_PASSWORD_CHANGE',
    ETH_ACCOUNT_REMOVE: 'ETH_ACCOUNT_REMOVE',
    ETH_ACCOUNT_UPDATE_NAME: 'ETH_ACCOUNT_UPDATE_NAME',
    ETH_ACCOUNT_UPDATE_BALANCE: 'ETH_ACCOUNT_UPDATE_BALANCE',
    ETH_UPDATE_EXCHANGE_RATE: 'ETH_UPDATE_EXCHANGE_RATE',
    ETH_ACCOUNT_SUPPORT_TOKEN_ADD: 'ETH_ACCOUNT_SUPPORT_TOKEN_ADD',
    ETH_ACCOUNT_SUPPORT_TOKEN_REMOVE: 'ETH_ACCOUNT_SUPPORT_TOKEN_REMOVE',
    ETH_CURRENT_BLOCK_DATA: 'ETH_CURRENT_BLOCK_DATA',
    ETH_UPDATE_EOS_MAPPING_STATUS: 'ETH_UPDATE_EOS_MAPPING_STATUS',
    ETH_UPDATE_TRANSFER_GAS_LIMIT: 'ETH_UPDATE_TRANSFER_GAS_LIMIT',

    ETH_WALLET_INIT_PRIMARY_KEY: 'ETH_WALLET_INIT_PRIMARY_KEY'
};

export default ethActionTypes;