const walletActionTypes = {
    UPDATE_WALLET_SELF_INCREMENT_PRIMARY_KEY: "UPDATE_WALLET_SELF_INCREMENT_PRIMARY_KEY",
    UPDATE_WALLET_DEFAULT_PRIMARY_KEY: "UPDATE_WALLET_DEFAULT_PRIMARY_KEY",

    ACCOUNT_SET_DEFAULT: 'ACCOUNT_SET_DEFAULT',

    RE_CALC_CURRENT_WALLET_ADDRESS: 'RE_CALC_CURRENT_WALLET_ADDRESS',
};

export default walletActionTypes;