const chainActionTypes = {
    UPDATE_BTN_STATE: "UPDATE_BTN_STATE",
    CHANGE_CURRENT_CHAIN: "CHANGE_CURRENT_CHAIN",
    UPDATE_CHAIN_DATA: "UPDATE_CHAIN_DATA",
    UPDATE_SIDECHAIN_NODES: "UPDATE_SIDECHAIN_NODES",
    CHANGE_CURRENT_SIDECHAIN_NODE: "CHANGE_CURRENT_SIDECHAIN_NODE",
    UPDATE_SIDECHAIN_TOKENS: "UPDATE_SIDECHAIN_TOKENS"
};

export default chainActionTypes;
